### ISSUE TITLE
Problème de chargement des images en mode grille

### ISSUE THREAD

**Issue by Sylvain-Chu** [cherifad/CrousTillant#3]
Les images ne chargent pas en mode grille. ()

![image](https://github.com/cherifad/SmartRU/assets/56892538/44b13a35-09b1-4cfc-a09d-d0570556a46c)

**Comment by cherifad** [comment]
8be6d041229106bf9650835920cd85491b71c6d7

**Comment by Sylvain-Chu** [comment]
T'as fuis le problème.... ca compte pas.
