### ISSUE TITLE
Huston, on a un problème

### ISSUE THREAD

**Issue by MathisBzn** [cherifad/CrousTillant#7]
![image](https://github.com/cherifad/CrousTillant/assets/80400365/4f4cb012-00ff-4f7f-8b66-c731a5718f8b)
L'agrandissement des jours du calendriers avec les différents menus ne rend pas très bien. Sinon le site est genial !!!!!!!

**Comment by cherifad** [comment]
8be6d041229106bf9650835920cd85491b71c6d7
